iyuuToken = "" # iyuu token。用于自动辅种功能
#siteProxy = "http://127.0.0.1:1080" # 使用代理访问 PT 站点。（不适用于访问 BT 客户端）
#userAgent = "" #  所有站点默认使用的 ua。
#brushEnableStats = false # 启用刷流统计功能
#treatZeroFreeDiskSpaceAsError = false # 如启用。BT客户端返回的硬盘剩余空间“0”将被认为是错误值。

[[clients]]
name = "local"
type = "qbittorrent"
url = "http://localhost:8085/"
username = "admin"
password = "adminadmin"
#qbittorrentNoLogin = true # 如果启用，不会发送登录请求。这将提高命令响应速度。需要在 QB Web UI设置里开启跳过验证。
#brushMinDiskSpace = "5GB" # 刷流：保留最小空闲磁盘空间。
#brushSlowUploadSpeedTier = "100KB" # 刷流：上传速度持续低于此值的种子将可能被删除
#brushMaxDownloadingTorrents = 6 # 刷流：位于下载状态的种子数上限
#brushMaxTorrents = 50 # 刷流：种子数（所有状态）上限
#brushMinRatio = 0.2 # 刷流：最小上传/下载量比例
#brushDefaultUploadSpeedLimit = "10MB" # 刷流：默认最大上传速度限制(/s)
#brushTorrentSizeLimit = "1PB" #刷流：种子大小限制。大小超过此值的种子不会被选择。

[[sites]]
type = "mteam"
cookie = "cookie_here"
#proxy = "http://127.0.0.1:1080" # 访问该站点使用的代理。优先级高于全局的 siteProxy 配置。
#userAgent = "" # 部分站点 cookie 绑定 ua。默认使用 Chrome ua。
#torrentUploadSpeedLimit = "10MiB" # 站点单个种子上传速度限制。默认 10MiB/s
#brushUrl = "https://kp.m-team.cc/adult.php" # 单独设置刷流种子列表页 url。如不指定，np 使用 torrents.php
#timezone = "Asia/Shanghai" # 网站页面显示时间的时区
